<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit130b0461ff7cb7f70aee8af03626fa8b
{
    public static $prefixLengthsPsr4 = array (
        'S' => 
        array (
            'Stripe\\' => 7,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'Stripe\\' => 
        array (
            0 => __DIR__ . '/..' . '/stripe/stripe-php/lib',
        ),
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit130b0461ff7cb7f70aee8af03626fa8b::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit130b0461ff7cb7f70aee8af03626fa8b::$prefixDirsPsr4;

        }, null, ClassLoader::class);
    }
}
